package pi.Principal;


import janelas.cliAlterar;
import janelas.cliBuscar;
import janelas.cliCadastrar;
import janelas.cliDeletar;
import janelas.prodAlterar;
import janelas.prodBuscar;
import janelas.prodCadastrar;
import janelas.prodDeletar;
import java.awt.CardLayout;
import java.awt.Dimension;
import static java.awt.SystemColor.desktop;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Vinicius
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public MenuPrincipal() {
        initComponents();
    }
    
    private prodCadastrar produtoCadastrar = null;
    private prodAlterar produtoAlterar = null;
    private prodBuscar produtoBuscar = null;
    private prodDeletar produtoDeletar = null;
    private cliCadastrar clienteCadastrar = null;
    private cliAlterar clienteAlterar = null;
    private cliBuscar clienteBuscar = null;
    private cliDeletar clienteDeletar = null;
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelClientes = new javax.swing.JPanel();
        panelBotoesCli = new javax.swing.JPanel();
        btRegistrosCli = new javax.swing.JButton();
        btDeletarCli = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btCadastrarCli = new javax.swing.JButton();
        btBuscarCli = new javax.swing.JButton();
        btAlterarCli = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        desktopCli = new javax.swing.JDesktopPane();
        panelProdutos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelBotoesCli1 = new javax.swing.JPanel();
        btBuscarPro = new javax.swing.JButton();
        btAlterarPro = new javax.swing.JButton();
        btRegistrosProd = new javax.swing.JButton();
        btDeletarPro = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btCadastrarPro = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        panelVendas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(880, 700));

        panelClientes.setBackground(new java.awt.Color(255, 255, 255));

        panelBotoesCli.setBorder(javax.swing.BorderFactory.createTitledBorder("Funções "));

        btRegistrosCli.setBackground(new java.awt.Color(11, 15, 127));
        btRegistrosCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/listIcon.png"))); // NOI18N
        btRegistrosCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrosCliActionPerformed(evt);
            }
        });

        btDeletarCli.setBackground(new java.awt.Color(11, 15, 127));
        btDeletarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/deleteIcon.png"))); // NOI18N
        btDeletarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarCliActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(91, 91, 91));
        jLabel18.setText("Deletar");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(91, 91, 91));
        jLabel19.setText("Relatório");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(91, 91, 91));
        jLabel20.setText("Cadastrar");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(91, 91, 91));
        jLabel21.setText("Buscar");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(91, 91, 91));
        jLabel22.setText("Alterar");

        btCadastrarCli.setBackground(new java.awt.Color(11, 15, 127));
        btCadastrarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeAdicionarCliente.png"))); // NOI18N
        btCadastrarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarCliActionPerformed(evt);
            }
        });

        btBuscarCli.setBackground(new java.awt.Color(11, 15, 127));
        btBuscarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BuscarIcon.png"))); // NOI18N
        btBuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarCliActionPerformed(evt);
            }
        });

        btAlterarCli.setBackground(new java.awt.Color(11, 15, 127));
        btAlterarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeAlterar.png"))); // NOI18N
        btAlterarCli.setToolTipText("");
        btAlterarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesCliLayout = new javax.swing.GroupLayout(panelBotoesCli);
        panelBotoesCli.setLayout(panelBotoesCliLayout);
        panelBotoesCliLayout.setHorizontalGroup(
            panelBotoesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesCliLayout.createSequentialGroup()
                .addGroup(panelBotoesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotoesCliLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btCadastrarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btBuscarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btAlterarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBotoesCliLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel20)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel21)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel22)))
                .addGroup(panelBotoesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotoesCliLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btDeletarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotoesCliLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGap(103, 103, 103)))
                .addGroup(panelBotoesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRegistrosCli, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBotoesCliLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelBotoesCliLayout.setVerticalGroup(
            panelBotoesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotoesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegistrosCli, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDeletarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBotoesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBotoesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22)
                        .addComponent(jLabel19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel2.setText("PEREBA SPORTS");

        desktopCli.setToolTipText("");

        javax.swing.GroupLayout desktopCliLayout = new javax.swing.GroupLayout(desktopCli);
        desktopCli.setLayout(desktopCliLayout);
        desktopCliLayout.setHorizontalGroup(
            desktopCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopCliLayout.setVerticalGroup(
            desktopCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotoesCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopCli)
                .addContainerGap())
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(panelBotoesCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopCli)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clientes", panelClientes);

        panelProdutos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel3.setText("PEREBA SPORTS");

        panelBotoesCli1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Funções"), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(11, 15, 127))); // NOI18N

        btBuscarPro.setBackground(new java.awt.Color(11, 15, 127));
        btBuscarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BuscarIcon.png"))); // NOI18N
        btBuscarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarProActionPerformed(evt);
            }
        });

        btAlterarPro.setBackground(new java.awt.Color(11, 15, 127));
        btAlterarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeAlterar.png"))); // NOI18N
        btAlterarPro.setToolTipText("");
        btAlterarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarProActionPerformed(evt);
            }
        });

        btRegistrosProd.setBackground(new java.awt.Color(11, 15, 127));
        btRegistrosProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/listIcon.png"))); // NOI18N
        btRegistrosProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrosProdActionPerformed(evt);
            }
        });

        btDeletarPro.setBackground(new java.awt.Color(11, 15, 127));
        btDeletarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/deleteIcon.png"))); // NOI18N
        btDeletarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarProActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(91, 91, 91));
        jLabel13.setText("Deletar");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(91, 91, 91));
        jLabel14.setText("Relatório");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(91, 91, 91));
        jLabel15.setText("Cadastrar");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(91, 91, 91));
        jLabel16.setText("Buscar");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(91, 91, 91));
        jLabel17.setText("Alterar");

        btCadastrarPro.setBackground(new java.awt.Color(11, 15, 127));
        btCadastrarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeAdicionarCliente.png"))); // NOI18N
        btCadastrarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesCli1Layout = new javax.swing.GroupLayout(panelBotoesCli1);
        panelBotoesCli1.setLayout(panelBotoesCli1Layout);
        panelBotoesCli1Layout.setHorizontalGroup(
            panelBotoesCli1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesCli1Layout.createSequentialGroup()
                .addGroup(panelBotoesCli1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotoesCli1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btCadastrarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btBuscarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btAlterarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBotoesCli1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel15)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel16)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel17)))
                .addGroup(panelBotoesCli1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotoesCli1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btDeletarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotoesCli1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(103, 103, 103)))
                .addGroup(panelBotoesCli1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRegistrosProd, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBotoesCli1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelBotoesCli1Layout.setVerticalGroup(
            panelBotoesCli1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesCli1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotoesCli1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegistrosProd, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDeletarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBotoesCli1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBotoesCli1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelProdutosLayout = new javax.swing.GroupLayout(panelProdutos);
        panelProdutos.setLayout(panelProdutosLayout);
        panelProdutosLayout.setHorizontalGroup(
            panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotoesCli1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelProdutosLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        panelProdutosLayout.setVerticalGroup(
            panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(panelBotoesCli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Produtos", panelProdutos);

        panelVendas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/settings.png"))); // NOI18N

        javax.swing.GroupLayout panelVendasLayout = new javax.swing.GroupLayout(panelVendas);
        panelVendas.setLayout(panelVendasLayout);
        panelVendasLayout.setHorizontalGroup(
            panelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVendasLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVendasLayout.setVerticalGroup(
            panelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVendasLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vendas", panelVendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarProActionPerformed
       
    }//GEN-LAST:event_btBuscarProActionPerformed

    private void btAlterarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarProActionPerformed
        
    }//GEN-LAST:event_btAlterarProActionPerformed

    private void btRegistrosProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrosProdActionPerformed
       
    }//GEN-LAST:event_btRegistrosProdActionPerformed

    private void btDeletarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarProActionPerformed
       
    }//GEN-LAST:event_btDeletarProActionPerformed

    private void btCadastrarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarProActionPerformed
        
    }//GEN-LAST:event_btCadastrarProActionPerformed
    
    
    
    private void btAlterarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarCliActionPerformed

    }//GEN-LAST:event_btAlterarCliActionPerformed

    private void btBuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarCliActionPerformed

    }//GEN-LAST:event_btBuscarCliActionPerformed

    
    private void btCadastrarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarCliActionPerformed
            cliCadastrar a = new cliCadastrar();
            a.setVisible(true);
    }//GEN-LAST:event_btCadastrarCliActionPerformed

  
    
    private void btDeletarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarCliActionPerformed

    }//GEN-LAST:event_btDeletarCliActionPerformed

    private void btRegistrosCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrosCliActionPerformed

    }//GEN-LAST:event_btRegistrosCliActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarCli;
    private javax.swing.JButton btAlterarPro;
    private javax.swing.JButton btBuscarCli;
    private javax.swing.JButton btBuscarPro;
    private javax.swing.JButton btCadastrarCli;
    private javax.swing.JButton btCadastrarPro;
    private javax.swing.JButton btDeletarCli;
    private javax.swing.JButton btDeletarPro;
    private javax.swing.JButton btRegistrosCli;
    private javax.swing.JButton btRegistrosProd;
    private javax.swing.JDesktopPane desktopCli;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelBotoesCli;
    private javax.swing.JPanel panelBotoesCli1;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelProdutos;
    private javax.swing.JPanel panelVendas;
    // End of variables declaration//GEN-END:variables

    
}
