/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import java.awt.Component;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pi.Encapsular.EncapsularProdutos;
import pi.Servicos.ServicoProdutos;

/**
 *
 * @author Home
 */
public class prodBuscar extends javax.swing.JPanel {
    prodBuscar formBuscaProd = new prodBuscar();
    String ultimaBusca = null;
    private Component rootPane;
    /**
     * Creates new form prodBuscar
     */
    
    public prodBuscar() {
        initComponents();
        //Faz com que a coluna do ID não seja mostrada ao usuário.
        tbBuscarPro.getColumnModel().getColumn(0).setMinWidth(0);
        tbBuscarPro.getColumnModel().getColumn(0).setMaxWidth(0);
        tbBuscarPro.getColumnModel().getColumn(0).setWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuscarPro = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        comboBuscarPro = new javax.swing.JComboBox<>();
        tfBuscarProPanel = new javax.swing.JTextField();
        btBuscarProdAlterar = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        tbBuscarPro = new javax.swing.JTable();
        btBuscarProPanel1 = new javax.swing.JButton();

        javax.swing.GroupLayout panelBuscarProLayout = new javax.swing.GroupLayout(panelBuscarPro);
        panelBuscarPro.setLayout(panelBuscarProLayout);
        panelBuscarProLayout.setHorizontalGroup(
            panelBuscarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        panelBuscarProLayout.setVerticalGroup(
            panelBuscarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Buscar Produto");

        comboBuscarPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código do Produto", "Nome do  Produto" }));
        comboBuscarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBuscarProActionPerformed(evt);
            }
        });

        btBuscarProdAlterar.setText("Alterar");

        tbBuscarPro.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(11, 15, 127)));
        tbBuscarPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código do Produto", "Nome do Produto", "Catgoria", "Tamanho", "Cor", "Quantidade", "Preço", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane14.setViewportView(tbBuscarPro);

        btBuscarProPanel1.setText("Buscar");
        btBuscarProPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarProPanel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(comboBuscarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(tfBuscarProPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btBuscarProPanel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btBuscarProdAlterar)
                .addGap(89, 89, 89))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelBuscarPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel12)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBuscarProPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBuscarPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarProPanel1))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btBuscarProdAlterar)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 96, Short.MAX_VALUE)
                    .addComponent(panelBuscarPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 96, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBuscarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBuscarProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBuscarProActionPerformed

    private void btBuscarProPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarProPanel1ActionPerformed
      boolean resultSearch = false;
        
        //Grava o campo de pesquisa como a última pesquisa válida. O valor
        //de última pesquisa válida é utilizado na atualização da lista
        ultimaBusca = tfBuscarProPanel.getText();

        try {
            //Solicita a atualização da lista com o novo critério
            //de pesquisa (ultimaPesquisa)
            resultSearch = refreshList();
        } catch (Exception e) {
            //Exibe mensagens de erro na fonte de dados e para o listener
            JOptionPane.showMessageDialog(rootPane, e.getMessage(),
                    "Falha ao obter lista", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Exibe mensagem de erro caso a pesquisa não tenha resultados
        if (!resultSearch) {
            JOptionPane.showMessageDialog(rootPane, "A pesquisa não retornou resultados ",
                    "Sem resultados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btBuscarProPanel1ActionPerformed
     
    
    
    public boolean refreshList() throws SQLException, Exception {
        //Realiza a pesquisa de clientes com o último valor de pesquisa
        //para atualizar a lista
        List<EncapsularProdutos> resultado = ServicoProdutos.getInstance().
                procurar(ultimaBusca);

        //Obtém o elemento representante do conteúdo da tabela na tela
        DefaultTableModel model = (DefaultTableModel) tbBuscarPro.getModel();
        //Indica que a tabela deve excluir todos seus elementos
        //Isto limpará a lista, mesmo que a pesquisa não tenha sucesso
        model.setRowCount(0);

        //Verifica se não existiram resultados. Caso afirmativo, encerra a
        //atualização e indica ao elemento acionador o não sucesso da pesquisa
        if (resultado == null || resultado.size() <= 0) {
            return false;
        }

        //Percorre a lista de resultados e os adiciona na tabela
        for (int i = 0; i < resultado.size(); i++) {
            EncapsularProdutos produto = resultado.get(i);
            if (produto != null) {
                Object[] row = new Object[5];
                row[0] = produto.getCod_produto();
                row[1] = produto.getNm_produto();
                row[2] = produto.getCategoria();
                row[4] = produto.getPreco();
                row[5] = produto.getQtde();
                row[6] = produto.getDescricao();
                row[7] = produto.getCor();
                row[8] = produto.getTamanho();
                model.addRow(row);
            }
        }

        //Se chegamos até aqui, a pesquisa teve sucesso, então
        //retornamos "true" para o elemento acionante, indicando
        //que não devem ser exibidas mensagens de erro
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarProPanel1;
    private javax.swing.JButton btBuscarProdAlterar;
    private javax.swing.JComboBox<String> comboBuscarPro;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JPanel panelBuscarPro;
    private javax.swing.JTable tbBuscarPro;
    private javax.swing.JTextField tfBuscarProPanel;
    // End of variables declaration//GEN-END:variables
}
