/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import java.awt.Component;
import javax.swing.JOptionPane;
import pi.Encapsular.EncapsularProdutos;
import pi.Metodos.MetodosProdutos;
import pi.Servicos.ServicoProdutos;
/**
 *
 * @author Home
 */
public class prodAlterar extends javax.swing.JPanel {

     EncapsularProdutos produto = new EncapsularProdutos();
    private Component rootPane;
     
    /**
     * Creates new form prodAlterar
     */
    public prodAlterar() {
        initComponents();
    }
    
    public EncapsularProdutos getEncapsularProdutos() {
        return produto;
    }

    public void setEncapsularProdutos(EncapsularProdutos produto) {
        this.produto = produto;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCodProdutoPro = new javax.swing.JLabel();
        tfCodPro = new javax.swing.JTextField();
        lbNomeProd = new javax.swing.JLabel();
        jtfNomePro = new javax.swing.JTextField();
        lbTamanhoPro = new javax.swing.JLabel();
        tfTamanhoPro = new javax.swing.JTextField();
        jtfCorPro = new javax.swing.JTextField();
        lbCorProd = new javax.swing.JLabel();
        lbQuantidadeProd = new javax.swing.JLabel();
        tfQuantidadePro = new javax.swing.JTextField();
        lbSexoCli1 = new javax.swing.JLabel();
        comboCategoriaPro = new javax.swing.JComboBox<>();
        lbPrecoProd = new javax.swing.JLabel();
        tfPrecoPro = new javax.swing.JTextField();
        lbDescricaoProd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDescricaoPro = new javax.swing.JTextPane();
        btCadastrarProPanel = new javax.swing.JButton();
        btCancelarProPanel = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        lbCodProdutoPro.setText("Código do Produto:");

        lbNomeProd.setText("Nome Produto:");

        jtfNomePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeProActionPerformed(evt);
            }
        });

        lbTamanhoPro.setText("Tamanho:");

        lbCorProd.setText("Cor:");

        lbQuantidadeProd.setText("Quantidade:");

        lbSexoCli1.setText("Categoria:");

        comboCategoriaPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Infantil" }));

        lbPrecoProd.setText("Preço:");

        lbDescricaoProd.setText("Descrição:");

        jScrollPane1.setViewportView(tfDescricaoPro);

        btCadastrarProPanel.setText("Atualizar");
        btCadastrarProPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarProPanelActionPerformed(evt);
            }
        });

        btCancelarProPanel.setText("Cancelar");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setText("Alterar Produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(283, 283, 283))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCodProdutoPro)
                                    .addComponent(lbNomeProd)
                                    .addComponent(lbPrecoProd)
                                    .addComponent(lbTamanhoPro)
                                    .addComponent(lbDescricaoProd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPrecoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtfNomePro, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45)
                                                .addComponent(lbSexoCli1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfTamanhoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbCorProd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jtfCorPro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbQuantidadeProd)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfQuantidadePro)
                                            .addComponent(comboCategoriaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCadastrarProPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btCancelarProPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(104, 104, 104))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel23)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCodProdutoPro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNomePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomeProd)
                    .addComponent(lbSexoCli1)
                    .addComponent(comboCategoriaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTamanhoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTamanhoPro)
                    .addComponent(jtfCorPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCorProd)
                    .addComponent(lbQuantidadeProd)
                    .addComponent(tfQuantidadePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrecoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecoProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescricaoProd)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelarProPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrarProPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeProActionPerformed

    private void btCadastrarProPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarProPanelActionPerformed
      

        produto.setCod_produto(Integer.parseInt(tfCodPro.getText()));
        produto.setNm_produto(jtfNomePro.getText());
        produto.setTamanho(Integer.parseInt(tfTamanhoPro.getText()));
        produto.setQtde(Integer.parseInt(tfQuantidadePro.getText()));
        produto.setCor(jtfCorPro.getText());
        produto.setPreco(Float.parseFloat(tfPrecoPro.getText()));
        produto.setDescricao(tfDescricaoPro.getText());
        produto.setCategoria((String) comboCategoriaPro.getSelectedItem());

        try {

            MetodosProdutos.atualizar(produto);
        } catch (Exception e) {           

            JOptionPane.showMessageDialog(rootPane, e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btCadastrarProPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarProPanel;
    private javax.swing.JButton btCancelarProPanel;
    private javax.swing.JComboBox<String> comboCategoriaPro;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtfCorPro;
    private javax.swing.JTextField jtfNomePro;
    private javax.swing.JLabel lbCodProdutoPro;
    private javax.swing.JLabel lbCorProd;
    private javax.swing.JLabel lbDescricaoProd;
    private javax.swing.JLabel lbNomeProd;
    private javax.swing.JLabel lbPrecoProd;
    private javax.swing.JLabel lbQuantidadeProd;
    private javax.swing.JLabel lbSexoCli1;
    private javax.swing.JLabel lbTamanhoPro;
    private javax.swing.JTextField tfCodPro;
    private javax.swing.JTextPane tfDescricaoPro;
    private javax.swing.JTextField tfPrecoPro;
    private javax.swing.JTextField tfQuantidadePro;
    private javax.swing.JTextField tfTamanhoPro;
    // End of variables declaration//GEN-END:variables
}
